---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/categories":
    get:
      summary: list categories
      tags:
      - All Categories
      responses:
        '200':
          description: successful
  "/api/v1/customers":
    get:
      summary: list customers
      tags:
      - All Customer
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: example.com
