---
openapi: 3.0.1
info:
  title: API V2
  version: v2
paths: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: example.com
